# Generated by Django 2.0.3 on 2018-09-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180917_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='no_bioprojects',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='no_experiments',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='no_runs',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='size',
            field=models.BigIntegerField(default=4),
            preserve_default=False,
        ),
    ]
