# Generated by Django 2.0.3 on 2018-09-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180917_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='no_bioprojects',
            field=models.PositiveIntegerField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='no_experiments',
            field=models.PositiveIntegerField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='no_runs',
            field=models.PositiveIntegerField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='size',
            field=models.BigIntegerField(verbose_name=0),
        ),
    ]
