# Generated by Django 2.0.3 on 2018-09-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180917_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='no_bioprojects',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='no_experiments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='no_runs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
